### PR TITLE
Migrate to pyproject.toml and scikit-build-core

### PR DESCRIPTION
**Pull request by mochaaP**
build: switch to scikit-build-core, use gitmodules & peru, clarify license
build: use prebuilt Tcl/Tk from CPython, fontconfig from vcpkg on win32 msvc
ci: add cibuildwheel and dependabot

Tested on py3.12 Feodra Linux

See changes in <https://github.com/TkinterEP/python-tksvg/pull/6>

TODO:
- [ ] test runs on macOS & Win32

### CODE REVIEW

**Comment by rdbende** [comment]
Just skimmed through the changes. They mostly look good to me.

> fontconfig from vcpkg on win32 msvc

Why is this needed? Extrafont doesn't use fontconfig on Windows, it uses GDI

**Comment by mochaaP** [comment]
> Just skimmed through the changes. They mostly look good to me.
> 
> > fontconfig from vcpkg on win32 msvc
> 
> Why is this needed? Extrafont doesn't use fontconfig on Windows, it uses GDI

Ah I missed that. Will fix it later

**Comment by rdbende** [comment]
The README mentions it, but I have built  `extrafont` with Visual Studio multiple times, and I can confirm, that `fontconfig` isn't necessary.

**Comment by mochaaP** [comment]
cc @rdbende this should be the final changes

**Comment by mochaaP** [comment]
blocked by <https://github.com/actions/runner-images/issues/9441>

**Comment by rdbende** [comment]
From others' tests this seems to work fine. Let's see how the CI goes.

**Pull request merged**
